trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.15.0"
    displayName: "Install Node.js"

  - task: Npm@1
    displayName: "install"
    inputs:
      command: 'ci'
  - task: Npm@1
    displayName: "test"
    inputs:
      command: "custom"
      customCommand: "run test"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/cobertura-final.json'

  - task: Npm@1
    displayName: "build"
    inputs:
      command: "custom"
      customCommand: "run build"

  - task: PublishBuildArtifacts@1
    displayName: "publish"
    inputs:
      PathtoPublish: "dist"
      ArtifactName: "idvalidator"
      publishLocation: "Container"
